service: sqs-processor
variablesResolutionMode: 20210326
provider:
  lambdaHashingVersion: 20201221
  name: aws
  memorySize: 512
  timeout: 20
  region: us-west-2
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

functions:
  sqsProcessor:
    handler: src/sqs_processor.handler
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - sqs:ReceiveMessage
        Resource: "arn:aws:sqs:us-west-2:476985000721:s3-event-process-queue"
    events:
      - sqs: arn:aws:sqs:us-west-2:476985000721:s3-event-process-queue
