service: sqs-processor
variablesResolutionMode: 20210326
provider:
  lambdaHashingVersion: 20201221
  name: aws
  memorySize: 512
  timeout: 20
  region: us-west-2
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

resources:
  Resources:
    sqsProcessorRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /service-role/
        RoleName: SQSProcessorRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SQSProcessorPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - sqs:*
                  Resource: "*"

functions:
  sqsProcessor:
    handler: src/sqs_processor.handler
    role: sqsProcessorRole
    events:
      - sqs: arn:aws:sqs:us-west-2:476985000721:s3-event-process-queue
